// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL = conexão direta ao Supabase (sem pooler) — usada só pelo CLI para migrações
    // DATABASE_URL = conexão pooled (pgBouncer) — usada pelo app em produção/Vercel
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
