export type QuizQuestion = {
  id: number;
  question: string;
  options: [string, string, string, string];
  correctIndex: number;
  explanation: string;
  category: string;
};

export const quizQuestions: QuizQuestion[] = [
  {
    id: 1,
    question: "Qual é a medicação de escolha (1ª linha) no tratamento da anafilaxia e como deve ser administrada?",
    options: ["Adrenalina 1 mg/mL, 0,5 mg (0,5 mL), via IM, no músculo vasto lateral da coxa","Salbutamol spray 100 mcg/dose, inalatório","Hidrocortisona 100 mg, via EV, diluída em 100 mL de SF 0,9%","Prometazina 50 mg, via IM profunda"],
    correctIndex: 0,
    explanation: "O texto afirma que a Adrenalina 1 mg/mL é a 'medicação de escolha', aplicada 0,5 mg (0,5 mL) IM no vasto lateral da coxa, sendo a medicação de 1ª linha.",
    category: "Emergência",
  },
  {
    id: 2,
    question: "Na anafilaxia, de quanto em quanto tempo pode-se repetir a dose de adrenalina caso não haja melhora clínica?",
    options: ["A cada 30 minutos","A cada 10 minutos","A cada 5 minutos","A cada 20 minutos"],
    correctIndex: 2,
    explanation: "O texto diz: 'Pode-se repetir a dose a cada 5 minutos caso não haja melhora clínica.'",
    category: "Emergência",
  },
  {
    id: 3,
    question: "Segundo o protocolo de anafilaxia, por quanto tempo, no mínimo, o paciente deve permanecer em observação?",
    options: ["6 horas","12 horas","24 horas","2 horas"],
    correctIndex: 0,
    explanation: "O texto orienta: 'Manter paciente em observação por, no mínimo, 6 horas.'",
    category: "Emergência",
  },
  {
    id: 4,
    question: "Qual valor de glicemia é citado como critério diagnóstico de cetoacidose diabética (CAD)?",
    options: ["Maior ou igual a 300 mg/dL","Maior ou igual a 200 mg/dL","Maior ou igual a 250 mg/dL","Maior ou igual a 180 mg/dL"],
    correctIndex: 2,
    explanation: "O critério (1) do texto é: 'Glicemia elevada: maior ou igual a 250 mg/dl'.",
    category: "Emergência",
  },
  {
    id: 5,
    question: "Na correção do potássio na CAD, o que deve ser feito se o K estiver abaixo de 3,3 mEq/L?",
    options: ["Iniciar insulina em BIC imediatamente, sem repor K","Repor K apenas após 4 horas de insulina","Iniciar reposição de K antes do início da insulina em bomba de infusão","Aguardar novos exames antes de repor K"],
    correctIndex: 2,
    explanation: "O texto especifica: 'Se K < 3,3 mEq/L: iniciar reposição de K antes do início de insulina em bomba de infusão.'",
    category: "Emergência",
  },
  {
    id: 6,
    question: "Qual é a meta de variação da glicemia por hora ao titular a insulina em BIC no tratamento da CAD?",
    options: ["Entre 50 a 70 mg/dL por hora","Entre 10 a 20 mg/dL por hora","Entre 30 a 40 mg/dL por hora","Entre 100 a 150 mg/dL por hora"],
    correctIndex: 0,
    explanation: "O texto orienta: 'Titular a vazão da insulina em BIC a cada hora, objetivando variação da glicemia entre 50 a 70 mg/dL por hora.'",
    category: "Emergência",
  },
  {
    id: 7,
    question: "Qual valor de HGT é utilizado como critério diagnóstico de hipoglicemia no texto?",
    options: ["HGT < 80 mg/dL","HGT < 60 mg/dL","HGT < 50 mg/dL","HGT < 70 mg/dL"],
    correctIndex: 3,
    explanation: "O critério diagnóstico citado é: 'HGT < 70 mg/dL e/ou sintomas associados'.",
    category: "Emergência",
  },
  {
    id: 8,
    question: "Qual a conduta EV padrão para tratamento da hipoglicemia grave, segundo o texto?",
    options: ["Soro glicosado 5%, 500 mL em bolus","Glucagon 1 mg, via IM","Glicose hipertônica 50%, 01 ampola em bolus","Glicose hipertônica 50%, 03 ampolas em bolus (podendo usar 04 ampolas)"],
    correctIndex: 3,
    explanation: "O texto orienta: 'Infundir 03 ampolas em bolus. (Pode-se utilizar 04 ampolas).'",
    category: "Emergência",
  },
  {
    id: 9,
    question: "Qual medicação tópica é indicada para queimaduras, segundo o texto?",
    options: ["Ibuprofeno gel, 3x/dia","Dipirona pomada, 2x/dia","Sulfadiazina de prata pomada 10 mg/g, fina camada, 2x/dia, por 10 dias","Sulfadiazina de prata pomada, 1x/dia, por 5 dias"],
    correctIndex: 2,
    explanation: "O texto indica: 'Sulfadiazina de prata pomada ---- 10 mg/g. Aplicar fina camada na lesão, 2x/dia, por 10 dias.'",
    category: "Emergência",
  },
  {
    id: 10,
    question: "Qual a dose máxima diária de fosfato de codeína citada para dor forte e refratária em queimaduras?",
    options: ["480 mg/dia","360 mg/dia","240 mg/dia","600 mg/dia"],
    correctIndex: 1,
    explanation: "O texto diz: 'Tomar 01 comprimido, de 6/6h, caso dor forte e refratária à dipirona/paracetamol. Dose máxima: 360 mg/dia.'",
    category: "Emergência",
  },
  {
    id: 11,
    question: "Por quanto tempo deve-se lavar a região da queimadura com água corrente, segundo as orientações do texto?",
    options: ["5 minutos","1 hora","30 minutos","15 minutos"],
    correctIndex: 3,
    explanation: "O texto orienta: 'Lavar a região afetada com água corrente por 15 minutos após a queimadura.'",
    category: "Emergência",
  },
  {
    id: 12,
    question: "Qual o volume de cristaloide recomendado na ressuscitação volêmica imediata do pacote da 1ª hora na sepse?",
    options: ["10 mL/kg","20 mL/kg","30 mL/kg","50 mL/kg"],
    correctIndex: 2,
    explanation: "O texto indica: 'Ressuscitação volêmica imediata de 30 ml/kg de solução cristaloide.'",
    category: "Emergência",
  },
  {
    id: 13,
    question: "Qual é o vasopressor de primeira escolha na hipotensão refratária à expansão volêmica no choque séptico?",
    options: ["Vasopressina","Dobutamina","Adrenalina","Norepinefrina"],
    correctIndex: 3,
    explanation: "O texto afirma: 'O primeiro vasopressor de escolha em hipotensão refratária à expansão volêmica é a norepinefrina (choque séptico).'",
    category: "Emergência",
  },
  {
    id: 14,
    question: "Segundo o pacote da 1ª hora da sepse, em até quanto tempo o antimicrobiano deve ser iniciado?",
    options: ["Até 6 horas","Até 2 horas","Até 1 hora","Até 3 horas"],
    correctIndex: 2,
    explanation: "O texto diz: 'Deve ser iniciado em até 01 hora, não devendo ser prorrogado em caso de demora para coleta de cultura.'",
    category: "Emergência",
  },
  {
    id: 15,
    question: "Qual é a meta de saturação de oxigênio na oxigenioterapia da exacerbação de DPOC (protocolo ABCD)?",
    options: ["Acima de 95%","Entre 94-98%","Entre 85-88%","Entre 88-92%"],
    correctIndex: 3,
    explanation: "O texto orienta: 'Ofertar o menor fluxo necessário para alvo de saturação entre 88-92%.'",
    category: "Emergência",
  },
  {
    id: 16,
    question: "Como o texto define acidose respiratória como indicação de VNI na exacerbação de DPOC?",
    options: ["pH ≤ 7,35 e pCO2 > 50 mmHg","pH ≤ 7,30 e pCO2 > 60 mmHg","pH ≤ 7,20 e pCO2 > 40 mmHg","pH ≤ 7,00 e pCO2 > 80 mmHg"],
    correctIndex: 1,
    explanation: "O texto lista como indicação de VNI: 'Acidose respiratória (pH ≤ 7,30 e pCO2 > 60 mmHg).'",
    category: "Emergência",
  },
  {
    id: 17,
    question: "Qual é o esquema de corticoide oral no tratamento ABCD da exacerbação de DPOC?",
    options: ["Prednisona 40 mg, dose única","Prednisona 20 mg, 03 comprimidos por dia, por 3 dias","Prednisona 20 mg, 02 comprimidos por dia, por 5 dias","Prednisona 20 mg, 01 comprimido por dia, por 10 dias"],
    correctIndex: 2,
    explanation: "O texto indica: 'Prednisona ---- 20mg. Tomar 02 comprimidos por dia, por 5 dias.'",
    category: "Emergência",
  },
  {
    id: 18,
    question: "Segundo o texto, em quanto tempo a endoscopia digestiva alta deve ser realizada na suspeita de HDA varicosa?",
    options: ["Até 12 horas","Até 24 horas","Até 6 horas","Até 48 horas"],
    correctIndex: 0,
    explanation: "O texto orienta: 'Na suspeita de HDA varicosa, priorizar em até 12 horas.'",
    category: "Emergência",
  },
  {
    id: 19,
    question: "Qual a dose de ataque em bólus do Omeprazol EV no manejo da HDA?",
    options: ["120 mg (03 ampolas)","40 mg (01 ampola)","80 mg (02 ampolas)","20 mg"],
    correctIndex: 2,
    explanation: "O texto indica: 'Infundir 02 ampolas (80 mg) em bólus... seguido de 01 ampola (40 mg) de 12/12h.'",
    category: "Emergência",
  },
  {
    id: 20,
    question: "Qual o alvo geral de hemoglobina no suporte transfusional na HDA, segundo o texto?",
    options: ["Manter Hb > 9 g/dL","Manter Hb > 7 g/dL","Manter Hb > 12 g/dL","Manter Hb > 10 g/dL"],
    correctIndex: 1,
    explanation: "O texto diz: 'Manter Hb > 7 g/dL (ou entre 8-10 g/dL em cardiopatas).'",
    category: "Emergência",
  },
  {
    id: 21,
    question: "Em qual situação a fenitoína é indicada no manejo da crise convulsiva, segundo o texto?",
    options: ["Em toda primeira crise convulsiva","Em toda convulsão febril","Nunca é indicada em crise convulsiva","Em crises recorrentes ou estado de mal epiléptico"],
    correctIndex: 3,
    explanation: "O texto afirma: 'Não utilizar rotineiramente na primeira crise. Indicada em crises recorrentes ou quando o paciente não recupera o nível de consciência entre duas crises.'",
    category: "Emergência",
  },
  {
    id: 22,
    question: "Em qual solução a fenitoína deve ser diluída, segundo o texto?",
    options: ["Somente em SF 0,9%","Em água destilada pura","Em Ringer lactato","Em soro glicosado 5%"],
    correctIndex: 0,
    explanation: "O texto adverte: 'Diluir somente em SF 0,9%. O medicamento precipita em soro glicosado ou em acesso com soluções contendo glicose.'",
    category: "Emergência",
  },
  {
    id: 23,
    question: "Quantas vezes pode-se repetir o Diazepam EV em bolus na crise convulsiva, segundo o texto?",
    options: ["Não pode ser repetido","Mais 1 vez","Mais 4 vezes","Mais 2 vezes até cessar a crise"],
    correctIndex: 3,
    explanation: "O texto diz: 'Diluir 01 ampola em 08 mL de SF 0,9% e infundir em bolus. Pode repetir mais 2 vezes até cessar a crise.'",
    category: "Emergência",
  },
  {
    id: 24,
    question: "Qual a dose de AAS administrada em todos os casos de Síndrome Coronariana Aguda (SCA), segundo o texto?",
    options: ["162 mg","300 mg (03 comprimidos)","500 mg","100 mg (01 comprimido)"],
    correctIndex: 1,
    explanation: "O texto indica: 'Administrar 300 mg (03 comprimidos) em todos os casos de SCA.'",
    category: "Emergência",
  },
  {
    id: 25,
    question: "No IAM com supra de ST, em locais com disponibilidade de cateterismo de urgência, qual a dose de clopidogrel administrada no PA/PS?",
    options: ["300 mg","600 mg (08 comprimidos)","900 mg","75 mg"],
    correctIndex: 1,
    explanation: "O texto afirma: 'administrar 600 mg de clopidogrel no PA/PS' e detalha 'Tomar 08 comprimidos (600 mg) em dose única.'",
    category: "Emergência",
  },
  {
    id: 26,
    question: "Qual a dose de furosemida EV em bólus para paciente virgem de furosemida no edema agudo de pulmão (EAP)?",
    options: ["1 mg/kg","2 mg/kg","0,5 mg/kg","1,5 mg/kg"],
    correctIndex: 0,
    explanation: "O texto diz: 'Dose: 1 mg/kg EV em bólus (virgem de furosemida) ou 1,5 mg/kg (uso prévio).'",
    category: "Emergência",
  },
  {
    id: 27,
    question: "Segundo o texto, quais são as principais contraindicações ao uso de Nitroprussiato de sódio (Nipride) no EAP?",
    options: ["FC > 100 bpm","PAS < 90 mmHg e/ou estenose aórtica grave","Nenhuma contraindicação é citada","PAS > 180 mmHg"],
    correctIndex: 1,
    explanation: "O texto afirma: 'Contraindicado: PAS < 90 mmHg e/ou estenose aórtica grave.'",
    category: "Emergência",
  },
  {
    id: 28,
    question: "O que o texto afirma sobre o uso de morfina no manejo do EAP?",
    options: ["É totalmente contraindicada em qualquer situação","É a droga de primeira escolha no EAP","Não é droga de primeira escolha — aumenta o índice de intubação, internação e mortalidade","Deve substituir a furosemida"],
    correctIndex: 2,
    explanation: "O texto adverte: 'A morfina não é droga de primeira escolha no manejo de EAP — aumenta o índice de intubação orotraqueal, internação hospitalar e mortalidade.'",
    category: "Emergência",
  },
  {
    id: 29,
    question: "Qual a energia inicial para Cardioversão Elétrica Sincronizada em FA instável, segundo o texto?",
    options: ["200 Joules","50 Joules","360 Joules","100 Joules"],
    correctIndex: 0,
    explanation: "O texto indica: 'Realizar Cardioversão Elétrica Sincronizada, iniciando com 200 Joules, com sedoanalgesia.'",
    category: "Emergência",
  },
  {
    id: 30,
    question: "Qual a meta de frequência cardíaca no controle de FC da FA estável, segundo o texto?",
    options: ["Abaixo de 110 bpm em repouso","Abaixo de 100 bpm","Abaixo de 130 bpm","Abaixo de 90 bpm"],
    correctIndex: 0,
    explanation: "O texto diz: 'Alvo de FC abaixo de 110 bpm em repouso.'",
    category: "Emergência",
  },
  {
    id: 31,
    question: "A partir de qual pontuação no CHA2DS2-VA é indicação classe IA anticoagular o paciente com FA, segundo o texto?",
    options: ["≥ 3","≥ 2","= 0","≥ 1"],
    correctIndex: 1,
    explanation: "O texto afirma: 'Recomendação de anticoagular se CHA2DS2-VA ≥ 2 (indicação classe IA).'",
    category: "Emergência",
  },
  {
    id: 32,
    question: "Qual a dose inicial de adenosina EV para TSVP estável hemodinamicamente?",
    options: ["02 ampolas (12 mg)","01 ampola (3 mg)","03 ampolas (18 mg)","01 ampola (6 mg) em bolus"],
    correctIndex: 3,
    explanation: "O texto orienta: 'Infundir 01 ampola (6 mg) em bolus no acesso venoso mais proximal.'",
    category: "Emergência",
  },
  {
    id: 33,
    question: "Qual a dose acumulada máxima de adenosina no tratamento da TSVP, segundo o texto?",
    options: ["12 mg","30 mg (6+12+12)","24 mg","50 mg"],
    correctIndex: 1,
    explanation: "O texto especifica: 'Dose máxima acumulada: 30 mg (6+12+12).'",
    category: "Emergência",
  },
  {
    id: 34,
    question: "Qual a faixa de dose de noradrenalina no choque, segundo o texto?",
    options: ["0,01 a 0,1 mcg/kg/min","0,05 a 3,3 mcg/kg/min","1 a 10 mcg/kg/min","0,5 a 5 mcg/kg/min"],
    correctIndex: 1,
    explanation: "O texto indica: 'Dose no choque: 0,05 a 3,3 mcg/kg/min.'",
    category: "Emergência",
  },
  {
    id: 35,
    question: "Para quais indicações a dobutamina é utilizada, segundo o texto?",
    options: ["Choque hipovolêmico","Choque séptico","Choque cardiogênico e IC perfil C","Choque anafilático"],
    correctIndex: 2,
    explanation: "O texto afirma: 'Indicações: choque cardiogênico e IC perfil C.'",
    category: "Emergência",
  },
  {
    id: 36,
    question: "Qual a dose de vasopressina indicada no choque séptico refratário, segundo o texto?",
    options: ["0,1 a 0,4 UI/min","0,001 a 0,004 UI/min","0,01 a 0,04 UI/min","1 a 4 UI/min"],
    correctIndex: 2,
    explanation: "O texto diz: 'Dose no choque séptico: 0,01 a 0,04 UI/min.'",
    category: "Emergência",
  },
  {
    id: 37,
    question: "Qual é a concentração final da diluição padrão de noradrenalina descrita no texto (04 ampolas do Levophed® em 234 mL de SG 5%)?",
    options: ["128 mcg/mL","16 mcg/mL","32 mcg/mL","64 mcg/mL"],
    correctIndex: 3,
    explanation: "O texto afirma: 'Diluir 04 ampolas do Levophed® (16 mg) em 234 mL de SG 5%. Total: 250 mL = 64 mcg/mL.'",
    category: "Emergência",
  },
  {
    id: 38,
    question: "Por quanto tempo a noradrenalina pode ser usada em acesso venoso periférico, segundo o texto?",
    options: ["Até 12 horas","Até 48 horas","Até 24 horas","Até 72 horas"],
    correctIndex: 3,
    explanation: "O texto diz: 'Pode usar em acesso venoso periférico por até 72 horas.'",
    category: "Emergência",
  },
  {
    id: 39,
    question: "Qual medicação NÃO deve ser administrada no mesmo acesso que a noradrenalina, segundo o texto?",
    options: ["Água destilada","Bicarbonato de sódio (inativação química)","SG 5%","SF 0,9%"],
    correctIndex: 1,
    explanation: "O texto adverte: 'Não administrar com bicarbonato de sódio no mesmo acesso (inativação química).'",
    category: "Emergência",
  },
  {
    id: 40,
    question: "Qual a pressão de pico máxima tolerada na ventilação controlada por volume (VCV), segundo o texto?",
    options: ["40 cmH2O","50 cmH2O","20 cmH2O","30 cmH2O"],
    correctIndex: 3,
    explanation: "O texto orienta: 'Tolerar pressão de pico máxima de 30 cmH2O.'",
    category: "Emergência",
  },
  {
    id: 41,
    question: "Qual o volume corrente alvo na ventilação controlada por volume (VCV), segundo o texto?",
    options: ["4 mL/kg","8 mL/kg","10 mL/kg","6 mL/kg de peso predito"],
    correctIndex: 3,
    explanation: "O texto diz: 'Volume alvo: 6 mL/kg de peso predito.'",
    category: "Emergência",
  },
  {
    id: 42,
    question: "Qual o FiO2 inicial recomendado nos parâmetros de VM invasiva, tanto em PCV quanto VCV?",
    options: ["60%","100%","21%","50%"],
    correctIndex: 1,
    explanation: "A tabela de parâmetros iniciais lista 'FiO2 | 100%' tanto para PCV quanto VCV.",
    category: "Emergência",
  },
  {
    id: 43,
    question: "Qual a dose de fentanil utilizada na etapa de analgesia da sequência rápida de intubação (ISR)?",
    options: ["10–20 µg/kg","1–3 µg/kg","0,1–0,3 µg/kg","5–10 µg/kg"],
    correctIndex: 1,
    explanation: "O texto indica: 'Fentanil ---- 1–3 µg/kg. Infundir lentamente em no mínimo 1 minuto.'",
    category: "Emergência",
  },
  {
    id: 44,
    question: "Em quais situações a succinilcolina é contraindicada, segundo o texto da ISR?",
    options: ["Gestação","Asma brônquica","DPOC","Hipercalemia, histórico de hipertermia maligna e grandes queimados"],
    correctIndex: 3,
    explanation: "O texto alerta: 'Contraindicar succinilcolina em hipercalemia, histórico de hipertermia maligna e grandes queimados.'",
    category: "Emergência",
  },
  {
    id: 45,
    question: "Quais sedativos são descritos como cardioestáveis, preferíveis em pacientes hipotensos na ISR?",
    options: ["Propofol e Etomidato","Fentanil e Midazolam","Etomidato e Quetamina","Midazolam e Propofol"],
    correctIndex: 2,
    explanation: "O texto afirma: 'Etomidato e quetamina são cardioestáveis — preferir em hipotensos.'",
    category: "Emergência",
  },
  {
    id: 46,
    question: "Como é administrada a Fosfomicina trometamol 3g, segundo o texto?",
    options: ["01 sachê de 8/8h","01 comprimido de 12/12h por 7 dias","01 comprimido, dose única semanal","Diluir 01 sachê em 01 copo de água e ingerir em dose única"],
    correctIndex: 3,
    explanation: "O texto orienta: 'Diluir o conteúdo de 01 sachê em 01 copo de água (aprox. 100 ml) e ingerir em dose única.'",
    category: "Temas PS/UPA",
  },
  {
    id: 47,
    question: "Para qual indicação a Vancomicina oral (F/A diluída) é utilizada, segundo o texto?",
    options: ["ITU","Infecções por Clostridium difficile","Celulite","Pneumonia comunitária"],
    correctIndex: 1,
    explanation: "O texto especifica: 'Vancomicina 500 mg F/A (para infecções por Clostridium Difficile)... VO (ou por SNE), de 6/6h, por 10 dias.'",
    category: "Temas PS/UPA",
  },
  {
    id: 48,
    question: "Qual a via de administração da Penicilina G Benzatina, segundo o texto?",
    options: ["Via oral","Via subcutânea","Via EV","Via IM profunda (máx. 1 dose por glúteo)"],
    correctIndex: 3,
    explanation: "O texto orienta: 'Administrar via IM profunda (máx. 1 dose por glúteo).'",
    category: "Temas PS/UPA",
  },
  {
    id: 49,
    question: "Qual a classificação de risco na gestação atribuída à dipirona, segundo o texto?",
    options: ["Classe B","Risco D — contraindicada na gestação","Classe C","Liberada na gestação"],
    correctIndex: 1,
    explanation: "O texto afirma: 'Contraindicada na gestação (Risco D).'",
    category: "Temas PS/UPA",
  },
  {
    id: 50,
    question: "Qual o antídoto citado para intoxicação por paracetamol?",
    options: ["Vitamina K","N-Acetilcisteína","Naloxona","Flumazenil"],
    correctIndex: 1,
    explanation: "O texto diz: 'Antídoto: N-Acetilcisteína (regenera a glutationa hepática).'",
    category: "Temas PS/UPA",
  },
  {
    id: 51,
    question: "Qual a equivalência de dose entre morfina EV e VO, segundo o texto de opioides fortes?",
    options: ["1 mg EV = 1 mg VO","1 mg EV = 5 mg VO","1 mg de morfina EV = 3 mg VO","1 mg EV = 10 mg VO"],
    correctIndex: 2,
    explanation: "O texto afirma: 'Equivalência: 1 mg de morfina EV = 3 mg VO.'",
    category: "Temas PS/UPA",
  },
  {
    id: 52,
    question: "Por que se deve evitar ondansetrona em pacientes usando tramadol, segundo o texto?",
    options: ["Ondansetrona reduz a eficácia analgésica do tramadol","Potencializa a sedação de forma perigosa","Aumenta o risco de sangramento","Causa hipotensão grave"],
    correctIndex: 0,
    explanation: "O texto orienta: 'Ondansetrona reduz a eficácia analgésica do Tramadol. Prefira Metoclopramida ou Dimenidrinato como antiemético.'",
    category: "Temas PS/UPA",
  },
  {
    id: 53,
    question: "A partir de qual pontuação no Score de Padua está indicada profilaxia farmacológica associada à mecânica?",
    options: ["Pontuação ≥ 2","Pontuação ≥ 6","Pontuação ≥ 1","Pontuação ≥ 4"],
    correctIndex: 3,
    explanation: "O texto afirma: 'Pontuação ≥ 4: profilaxia mecânica + profilaxia farmacológica (se não houver contraindicação).'",
    category: "Temas PS/UPA",
  },
  {
    id: 54,
    question: "Qual a dose padrão de Enoxaparina para profilaxia de TEV em paciente com ClCr ≥ 30, segundo o texto?",
    options: ["40 mg, de 12/12h","40 mg, via SC, uma vez ao dia","20 mg, uma vez ao dia","60 mg, de 12/12h"],
    correctIndex: 1,
    explanation: "O texto orienta: 'Enoxaparina 40 mg (ClCr ≥ 30). Administrar 01 ampola, via SC, uma vez ao dia.'",
    category: "Temas PS/UPA",
  },
  {
    id: 55,
    question: "Quais critérios (2 ou mais presentes) indicam redução da dose de Apixabana para 2,5 mg de 12/12h na FA, segundo o texto?",
    options: ["Idade ≥ 65 anos, peso ≤ 70 kg, creatinina ≥ 1,0 mg/dL","Apenas peso ≤ 60 kg","Apenas idade ≥ 80 anos","Idade ≥ 80 anos, peso ≤ 60 kg, creatinina ≥ 1,5 mg/dL"],
    correctIndex: 3,
    explanation: "O texto lista os critérios: 'Idade ≥ 80 anos / Peso ≤ 60 kg / Creatinina ≥ 1,5 mg/dL' — reduzir se 2 ou mais presentes.",
    category: "Temas PS/UPA",
  },
  {
    id: 56,
    question: "Qual a dose inicial de Loperamida no manejo da GECA, segundo o texto?",
    options: ["02 mg (1 comprimido)","08 mg (4 comprimidos)","01 mg","04 mg (2 comprimidos)"],
    correctIndex: 3,
    explanation: "O texto orienta: 'Tomar dose inicial de 04 mg (2 comprimidos). Após cada evacuação líquida, mais 01 comprimido.'",
    category: "Temas PS/UPA",
  },
  {
    id: 57,
    question: "Qual a dose máxima diária de Loperamida citada no texto?",
    options: ["8 mg/dia","32 mg/dia","16 mg/dia (8 comprimidos)","24 mg/dia"],
    correctIndex: 2,
    explanation: "O texto especifica: 'Máximo: 08 comprimidos por dia (16 mg/dia).'",
    category: "Temas PS/UPA",
  },
  {
    id: 58,
    question: "Como deve ser reconstituído o soro de reidratação oral (SRO), segundo o texto?",
    options: ["Diluir 01 sachê em 01 litro de água filtrada","Diluir 01 sachê em 200 mL de água","Diluir 02 sachês em 01 litro de água","Diluir 01 sachê em 500 mL de água"],
    correctIndex: 0,
    explanation: "O texto orienta: 'Diluir em 01 litro de água filtrada. Repor 120 a 240 ml por episódio de diarreia ou vômito.'",
    category: "Temas PS/UPA",
  },
  {
    id: 59,
    question: "Qual conduta geral é recomendada para o manejo da pancreatite aguda, segundo o texto?",
    options: ["Alta imediata com retorno em 7 dias","Internação hospitalar, com dieta hipolipídica, hidratação venosa e controle sintomático","Tratamento ambulatorial com analgesia oral","Observação de 6 horas apenas no PS"],
    correctIndex: 1,
    explanation: "O texto afirma: 'Recomendamos internação hospitalar. A terapêutica envolve dieta hipolipídica, hidratação venosa e controle sintomático adequado.'",
    category: "Temas PS/UPA",
  },
  {
    id: 60,
    question: "Qual tipo de dieta é recomendada na pancreatite aguda, segundo o texto?",
    options: ["Dieta hipolipídica","Dieta rica em fibras","Dieta hiperproteica","Dieta hipossódica"],
    correctIndex: 0,
    explanation: "O texto indica explicitamente 'dieta hipolipídica' como parte da terapêutica.",
    category: "Temas PS/UPA",
  },
  {
    id: 61,
    question: "Quando está indicada a profilaxia com Amitriptilina para cefaleia tensional, segundo o texto?",
    options: ["Apenas na enxaqueca","Mais de 2 episódios por semana","Em toda cefaleia, independente da frequência","Nunca é indicada para cefaleia tensional"],
    correctIndex: 1,
    explanation: "O texto indica: 'Indicação: mais de 2 episódios por semana — droga de escolha: Amitriptilina.'",
    category: "Temas PS/UPA",
  },
  {
    id: 62,
    question: "Qual a dose máxima de Sumatriptano subcutâneo em 24 horas, segundo o texto?",
    options: ["6 mg (01 ampola)","12 mg (02 ampolas)","18 mg","24 mg"],
    correctIndex: 1,
    explanation: "O texto especifica: 'Dose máxima em 24h: 12 mg (02 ampolas).'",
    category: "Temas PS/UPA",
  },
  {
    id: 63,
    question: "Qual a abordagem de primeira linha para cefaleia em salvas, segundo o texto?",
    options: ["Oxigênio 100%, 10 a 12 L/min, máscara não-reinalante, por 10 a 20 minutos","Ventilação não invasiva (VNI)","Nenhuma oxigenioterapia é indicada","Cateter nasal a 2 L/min"],
    correctIndex: 0,
    explanation: "O texto orienta: 'Oxigênio 100%, 10 a 12 L/min, máscara não-reinalante, por 10 a 20 minutos.'",
    category: "Temas PS/UPA",
  },
  {
    id: 64,
    question: "Qual a meta geral de saturação de O2 na crise de asma, segundo o texto?",
    options: ["Acima de 92%","Acima de 85%","Acima de 98%","Acima de 88%"],
    correctIndex: 0,
    explanation: "O texto afirma: 'Meta de saturação > 92% — crianças e gestantes: > 95%.'",
    category: "Temas PS/UPA",
  },
  {
    id: 65,
    question: "Em qual situação o Sulfato de Magnésio é indicado na crise de asma, segundo o texto?",
    options: ["Toda crise leve","Toda crise, independente da gravidade","Exacerbação grave","Apenas em crianças"],
    correctIndex: 2,
    explanation: "O texto lista o Sulfato de Magnésio sob o título 'Sulfato de Magnésio (exacerbação grave)'.",
    category: "Temas PS/UPA",
  },
  {
    id: 66,
    question: "Qual corticoide inalatório é citado como alternativa disponível pelo SUS na prescrição domiciliar da asma?",
    options: ["Budesonida isolada, sem associação","Fluticasona isolada","Formoterol+Budesonida isolado","Dipropionato de Beclometasona 50 mcg/dose"],
    correctIndex: 3,
    explanation: "O texto indica: 'Alternativa (SUS): Dipropionato de Beclometasona 50 mcg/dose. Inalar 04 jatos, de 12/12h.'",
    category: "Temas PS/UPA",
  },
  {
    id: 67,
    question: "Qual critério de gravidade é citado no texto como indicativo de internação na pneumonia comunitária?",
    options: ["CURB-65 ≥ 2","CURB-65 ≥ 1","Apenas idade avançada","Nenhum score é mencionado"],
    correctIndex: 0,
    explanation: "O texto afirma: 'Internação (CURB-65 ≥ 2 ou PSI/PORT).'",
    category: "Temas PS/UPA",
  },
  {
    id: 68,
    question: "Em paciente ambulatorial sem comorbidades, por quantos dias é feita a Azitromicina 500 mg, 1x/dia, na pneumonia comunitária?",
    options: ["05 dias","07 dias","03 dias","10 dias"],
    correctIndex: 0,
    explanation: "O texto orienta: 'Azitromicina 500 mg comprimido. Tomar 01 comprimido, 1 vez ao dia, por 05 dias.'",
    category: "Temas PS/UPA",
  },
  {
    id: 69,
    question: "Segundo o guideline IDSA 2025 citado no texto, como é classificada toda infecção urinária que se estende além da topografia da bexiga?",
    options: ["Bacteriúria assintomática","ITU complicada","ITU não complicada","Cistite simples"],
    correctIndex: 1,
    explanation: "O texto afirma: 'Guideline IDSA 2025: toda infecção urinária que se estende além da topografia da bexiga é considerada uma ITU complicada.'",
    category: "Temas PS/UPA",
  },
  {
    id: 70,
    question: "Como o texto define a cistite?",
    options: ["ITU alta (sintomas sistêmicos)","ITU baixa (sintomas localizados)","ITU complicada","Pielonefrite"],
    correctIndex: 1,
    explanation: "O texto define: 'Cistite — ITU baixa (sintomas localizados).'",
    category: "Temas PS/UPA",
  },
  {
    id: 71,
    question: "Segundo o texto, o uso de Oxacilina no tratamento hospitalar sem risco de MRSA é restrito a qual condição?",
    options: ["Ambas as condições igualmente","Apenas celulite, não erisipela","Apenas erisipela, não celulite","Nenhuma restrição é citada"],
    correctIndex: 1,
    explanation: "O texto especifica: 'Detalhes: *Oxacilina: utilizar apenas em caso de celulite (não erisipela).'",
    category: "Temas PS/UPA",
  },
  {
    id: 72,
    question: "Para pacientes ambulatoriais com risco de MRSA ou alergia a beta-lactâmicos, quais antibióticos orais são indicados?",
    options: ["Amoxicilina+Clavulanato","Cefalexina","Sulfametoxazol+Trimetoprima ou Doxiciclina","Penicilina G Benzatina"],
    correctIndex: 2,
    explanation: "O texto lista: 'Sulfametoxazol + Trimetoprima 800/160 mg... Ou Doxiciclina 100 mg' para pacientes com risco de MRSA ou alergia a beta-lactâmicos.",
    category: "Temas PS/UPA",
  },
  {
    id: 73,
    question: "Qual orientação de cuidado local é destacada para celulite e erisipela no texto?",
    options: ["Compressas quentes 3x ao dia","Aplicar pomada antibiótica tópica diariamente","Drenagem cirúrgica precoce em todos os casos","Higienização com água e sabão neutro, sem manipular ou romper bolhas"],
    correctIndex: 3,
    explanation: "O texto orienta: 'Cuidados locais: higienização com água e sabão neutro. Não manipular nem romper bolhas!'",
    category: "Temas PS/UPA",
  },
  {
    id: 74,
    question: "O que o texto orienta para casos graves de urticária, independente da via de administração do anti-histamínico?",
    options: ["Associar corticoide ao anti-histamínico","Dobrar a dose do anti-histamínico","Usar apenas adrenalina IM","Trocar por AINE"],
    correctIndex: 0,
    explanation: "O texto afirma: 'Em casos graves, associar corticoide ao anti-histamínico (independente da via utilizada).'",
    category: "Temas PS/UPA",
  },
  {
    id: 75,
    question: "Qual o esquema padrão de Loratadina 10 mg no tratamento da urticária, segundo o texto?",
    options: ["Dose única","01 comprimido à noite, por 5 dias","01 comprimido 3x/dia","01 comprimido de 12/12h, por 10 dias"],
    correctIndex: 1,
    explanation: "O texto orienta: 'Tomar 01 comprimido à noite, por 05 dias. (Em casos mais graves: 01 comprimido de 12/12h, por 5 dias.)'",
    category: "Temas PS/UPA",
  },
  {
    id: 76,
    question: "Qual laxante o texto orienta evitar em idosos e pacientes com disfagia?",
    options: ["Macrogol","Lactulose","Óleo mineral","Bisacodil"],
    correctIndex: 2,
    explanation: "O texto adverte, sobre óleo mineral: 'Evitar em idosos e pacientes com disfagia.'",
    category: "Temas PS/UPA",
  },
  {
    id: 77,
    question: "Segundo o texto, quando o uso do laxante deve ser interrompido?",
    options: ["Se houver diarreia","Nunca deve ser interrompido","Se houver dor abdominal leve","Após 30 dias de uso"],
    correctIndex: 0,
    explanation: "O texto orienta: 'Interromper o uso se diarreia.'",
    category: "Temas PS/UPA",
  },
  {
    id: 78,
    question: "Qual esquema antibiótico oral é indicado para diverticulite aguda não complicada, segundo o texto?",
    options: ["Ciprofloxacino 500 mg de 12/12h + Metronidazol 250 mg de 8/8h","Amoxicilina+Clavulanato isolado","Azitromicina + Metronidazol","Ceftriaxona isolada"],
    correctIndex: 0,
    explanation: "O texto indica: 'Ciprofloxacino 500 mg... de 12/12h, por 7 dias. + Metronidazol 250 mg... de 8/8h, por 7 dias.'",
    category: "Temas PS/UPA",
  },
  {
    id: 79,
    question: "Por quantos dias é feito o esquema antibiótico da diverticulite aguda não complicada, segundo o texto?",
    options: ["14 dias","10 dias","5 dias","7 dias"],
    correctIndex: 3,
    explanation: "O texto especifica '...por 7 dias' tanto para ciprofloxacino quanto metronidazol.",
    category: "Temas PS/UPA",
  },
  {
    id: 80,
    question: "Qual o momento recomendado para tomar o inibidor de bomba de prótons (IBP) no tratamento da DRGE, segundo o texto?",
    options: ["À noite, antes de dormir","Em jejum, 30 minutos antes do café da manhã","Junto das refeições","Após o almoço"],
    correctIndex: 1,
    explanation: "O texto orienta: 'Tomar 01 cápsula, em jejum, 30 minutos antes do café da manhã.'",
    category: "Temas PS/UPA",
  },
  {
    id: 81,
    question: "Qual procinético é associado ao IBP no tratamento da DRGE, segundo o texto?",
    options: ["Ondansetrona","Bromoprida","Domperidona 10 mg","Metoclopramida"],
    correctIndex: 2,
    explanation: "O texto indica: 'Associado a: Domperidona 10 mg. Tomar 01 comprimido, 20 minutos antes do café da manhã, do almoço e do jantar.'",
    category: "Temas PS/UPA",
  },
  {
    id: 82,
    question: "Por quantos dias é feito o esquema tríplice de erradicação do H. pylori descrito no texto?",
    options: ["10 dias","21 dias","7 dias","14 dias"],
    correctIndex: 3,
    explanation: "O texto lista: Omeprazol, Claritromicina e Amoxicilina, todos 'por 14 dias'.",
    category: "Temas PS/UPA",
  },
  {
    id: 83,
    question: "Após o esquema de erradicação do H. pylori, por quanto tempo o IBP deve ser mantido, segundo o texto?",
    options: ["Mais 4 semanas, na dose de 20 mg/dia","Mais 8 semanas","Mais 2 semanas","Não há necessidade de manutenção"],
    correctIndex: 0,
    explanation: "O texto orienta: 'Manter IBP por mais 04 semanas, na dose de 20 mg/dia, após o esquema de erradicação.'",
    category: "Temas PS/UPA",
  },
  {
    id: 84,
    question: "Quantos mg de ferro elementar equivalem a 300 mg de FeSO4, segundo o texto?",
    options: ["300 mg","30 mg","60 mg","100 mg"],
    correctIndex: 2,
    explanation: "O texto afirma: '300 mg de FeSO₄ = 60 mg de ferro elementar (equivale a 1/5 da dose total).'",
    category: "Temas PS/UPA",
  },
  {
    id: 85,
    question: "Qual o intervalo ideal entre as infusões EV de Sacarato de Hidróxido Férrico, segundo o texto?",
    options: ["A cada 24h","A cada 72h","A cada 12h","A cada 48h (dias alternados)"],
    correctIndex: 3,
    explanation: "O texto orienta: 'O ideal é que as infusões sejam realizadas a cada 48h (em dias alternados).'",
    category: "Temas PS/UPA",
  },
  {
    id: 86,
    question: "Qual classe de medicamentos deve ser evitada em dengue, zika e chikungunya, segundo o texto?",
    options: ["AINEs (ibuprofeno, nimesulida, diclofenaco, cetoprofeno, AAS)","Anti-histamínicos","Opioides","Antieméticos"],
    correctIndex: 0,
    explanation: "O texto orienta: 'Evitar AINES (ibuprofeno, nimesulida, diclofenaco, cetoprofeno, AAS) — contraindicados.'",
    category: "Temas PS/UPA",
  },
  {
    id: 87,
    question: "Qual a hidratação diária recomendada, segundo as orientações gerais do texto sobre dengue/zika/chikungunya?",
    options: ["30 a 40 mL/kg/dia","20 a 30 mL/kg/dia","100 a 120 mL/kg/dia","60 a 80 mL/kg/dia"],
    correctIndex: 3,
    explanation: "O texto orienta: 'Repouso e hidratação adequada (60 a 80 mL/kg/dia).'",
    category: "Temas PS/UPA",
  },
  {
    id: 88,
    question: "Qual a meta de saturação de oxigênio na exacerbação de DPOC (esquema ABCD), segundo o texto?",
    options: ["Entre 85 e 90%","Entre 94 e 98%","Entre 88 e 92%","Entre 90 e 95%"],
    correctIndex: 2,
    explanation: "O texto afirma: 'Alvo: saturação entre 88 e 92%.'",
    category: "Temas PS/UPA",
  },
  {
    id: 89,
    question: "Qual macrolídeo deve ser associado ao antimicrobiano de base na exacerbação de DPOC, segundo o texto?",
    options: ["Azitromicina por 10 dias","Claritromicina 500 mg, 12/12h","Azitromicina 500 mg, 1x/dia, por 5 dias","Eritromicina"],
    correctIndex: 2,
    explanation: "O texto orienta: 'Associar macrolídeo: Azitromicina 500 mg comprimido. Tomar 01 comprimido, 1 vez ao dia, por 05 dias.'",
    category: "Temas PS/UPA",
  },
  {
    id: 90,
    question: "Qual referência é citada no texto para a recomendação de Amoxicilina 500 mg de 8/8h por 10 dias na faringite estreptocócica?",
    options: ["UpToDate","OMS","CDC","CREMESP"],
    correctIndex: 0,
    explanation: "O texto afirma: 'Recomendação do UpToDate para Faringite Estreptocóccica.'",
    category: "Temas PS/UPA",
  },
  {
    id: 91,
    question: "Como é administrada a Penicilina G Benzatina na faringoamigdalite bacteriana, segundo o texto?",
    options: ["01 ampola, via IM, dose única","01 ampola de 12/12h por 10 dias","Via EV, dose única","01 ampola por semana"],
    correctIndex: 0,
    explanation: "O texto orienta: 'Administrar 01 ampola, via IM, dose única.'",
    category: "Temas PS/UPA",
  },
  {
    id: 92,
    question: "Com que frequência deve ser feita a lavagem nasal com soro fisiológico na sinusite bacteriana, segundo o texto?",
    options: ["2 vezes ao dia, por 10 dias","1 vez ao dia","6 vezes ao dia","4 vezes ao dia, por 5 dias"],
    correctIndex: 3,
    explanation: "O texto orienta: 'Lavar narinas, 4 vezes ao dia, por 05 dias.'",
    category: "Temas PS/UPA",
  },
  {
    id: 93,
    question: "Qual o esquema com Levofloxacino citado como opção para sinusite bacteriana, segundo o texto?",
    options: ["Levofloxacino 750 mg, dose única","Levofloxacino 500 mg, 12/12h, por 10 dias","Levofloxacino 250 mg, 1x/dia, por 14 dias","Levofloxacino 750 mg, 1 vez ao dia, por 7 dias"],
    correctIndex: 3,
    explanation: "O texto indica: 'Levofloxacino 750 mg. Tomar 01 comprimido, 1 vez ao dia, por 07 dias.'",
    category: "Temas PS/UPA",
  },
  {
    id: 94,
    question: "Por quantos dias é feito o tratamento com Levofloxacino 750 mg na otite média aguda bacteriana, segundo o texto?",
    options: ["05 dias","14 dias","07 dias","10 dias"],
    correctIndex: 0,
    explanation: "O texto orienta: 'Levofloxacino 750 mg. Tomar 01 comprimido, 1 vez ao dia, por 05 dias.'",
    category: "Temas PS/UPA",
  },
  {
    id: 95,
    question: "Qual o esquema de Axetilcefuroxima citado como opção para otite média aguda bacteriana, segundo o texto?",
    options: ["500 mg, 1x/dia, por 7 dias","250 mg, dose única","250 mg, de 12/12h, por 5 dias","500 mg, de 12/12h, por 10 dias"],
    correctIndex: 3,
    explanation: "O texto indica: 'Axetilcefuroxima 500 mg. Tomar 01 comprimido, de 12/12h, por 10 dias.'",
    category: "Temas PS/UPA",
  },
];

export function getDailyQuestions(dateStr: string): QuizQuestion[] {
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) {
    hash = ((hash << 5) - hash + dateStr.charCodeAt(i)) | 0;
  }
  hash = Math.abs(hash);

  const indices: number[] = [];
  const total = quizQuestions.length;
  let attempt = 0;
  while (indices.length < 5 && attempt < 100) {
    const idx = ((hash + attempt * 7 + attempt * attempt * 13) % total + total) % total;
    if (!indices.includes(idx)) indices.push(idx);
    attempt++;
  }

  return indices.map((i) => quizQuestions[i]);
}

export function getTodayDateStr(): string {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;
}

export function getQuizDateUTC(dateStr: string): Date {
  const [y, m, d] = dateStr.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d));
}
